version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=100GB'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  infrasd:
    image: stelsik/zabbix-prom-sd:latest
    environment:
      - ZABBIXURL=https://zabbix.host/
      - ZABBIXUSERNAME=username
      - ZABBIXPASSWORD=password
    volumes:
      - ./prometheus/targets/:/app/targets/
    restart: always
