# Here it's example Prometheus netdata scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'netdata-scrape'

    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    
    #Path to sd file
    file_sd_configs:
      - files:
        - targets/targets.json

    relabel_configs:
      - source_labels: [__address__]
        regex:  '(.*)(:\d+)?'
        target_label: __address__
        replacement: '${1}:19999'
